### ISSUE TITLE
Minor issue and a question

### ISSUE THREAD

**Issue by slyhne** [juho-jaakkola/elgg-notifier#13]
Really nice plugin :-)

How does it play with the core plugin site_notifications?

There is a page_handler for some pages, but aren't there missing a page menu, or links, to get to those pages?

**Comment by juho-jaakkola** [comment]
AFAIK It shouldn't conflict with site_notifications in any way. Then again it has all the same features and more. So there's really no point in having both enabled at the same time.

You can find the page links from the popup (assuming there is at least one notification).
