### ISSUE TITLE
friendsof links go to a 404

### ISSUE THREAD

**Issue by propertunist** [juho-jaakkola/elgg-notifier#17]
some entries in the notifier that refer to users making you a friend, point to a url that includes the handler 'friendsof'. i can see that there is a 'friendsof' handler defined in the notifier start.php file, however, on my site these URLs return a 404 not found error.
i have not changed this handler in pagehandler hijack and it actually isn't listed. i think this is because the friend_request plugin i am using removes 'friendsof' and replaces it with 'friend_request' - however, since notifier is after the 'friend request' plugin in my site's plugin list, i thought that this would not be an issue - yet it is.

**Comment by juho-jaakkola** [comment]
Well you said it - the 'friendsof' page is not found because friend_request plugin removes the 'friendsof' page handler. So you get 404 for it regardless if you use notifier or not.

I don't think there is any other URL that the notification could link to by default.

**Comment by propertunist** [comment]
i don't know enough about the intended schema for these types of notifications to know what the root of the issue is here. since i saw that the notifier plugin registers a friendsof handler, i thought that there would be no problem. i am not clear on why the friendsof handler is being used at all if it has been removed. basically, i don't know which plugin needs to be fixed - or why.

**Comment by juho-jaakkola** [comment]
Notifier doesn't register a page handler. I just observes whether the 'friendsof' page is displayed and marks the friends related notification as read when it happens.

I don't think your issue can be fixed within notifier. You need to add some kind of custom workaround for your site.

**Comment by propertunist** [comment]
aha, i see - ok - i didn't look closely enough at the code.. i am distracted here presently. i've raised an issue against the friend_request plugin.

**Comment by propertunist** [comment]
so it turned out that i needed to make a change to the file: notifier/messages/create/relationship/friend.php
there is a hardcoded URL in there that points to the friendsof page and i needed to add some logic to handle the existence of the friend request plugin:
```
                if (elgg_is_active_plugin('friend_request'))
                {
                        $friends_link = 'friends';
                }
                else
                {
                        $friends_link = 'friendsof';
                }
                
                $subjects_link = elgg_view('output/url', array(
                    'href' => "{$friends_link}/{$username}",
                    'text' => $subjects,
                    'is_trusted' => true,
                ));   
```

**Comment by propertunist** [comment]
or maybe you prefer to get friends_request to over-ride the notifier view?
