### ISSUE TITLE
Release 1.11.0 not working with elgg 1.12

### ISSUE THREAD

**Issue by oseg** [juho-jaakkola/elgg-notifier#31]
Hi Juho,

Just tested your latest release (1.11.0)  on elgg 1.12, and I noticed some small issues. To make it work on elgg v1.12, I had to change some code:

in start.php at line 30, I replace
`elgg_extend_view('elgg.css', 'notifier/notifier.css');`
by
`elgg_extend_view('css/elgg', 'notifier/notifier.css');`

in start.php at line 122, I replace
`echo elgg_view_resource('notifier/list');`
by
`echo elgg_view('resources/notifier/list');`

in start.php at line 127, I replace
`echo elgg_view_resource('notifier/subjects', array(`
by
`echo elgg_view('resources/notifier/subjects', array(`

I don't know if there is a way to make it work on both elgg 1.12 and elgg v2.2... maybe checking elgg version...

Regards,
Olivier

**Comment by juho-jaakkola** [comment]
It seems I have made a mistake at some point, and tagged the wrong version.

**Comment by juho-jaakkola** [comment]
Currently only the `1.10` branch work with Elgg `1.12.x`. The `1.x` branch has accidentally been made from the branch meant for Elgg 2.

**Comment by juho-jaakkola** [comment]
I've now removed both the `1.11.0` release and the `1.x` branch.
