### ISSUE TITLE
Looking for move the icon

### ISSUE THREAD

**Issue by annivzinal** [juho-jaakkola/elgg-notifier#34]
Hi

I am using notifier with Thime Theme pro from fernando Vega. 

It works but I want to move the icon of notifier to avoid this:

![image](https://cloud.githubusercontent.com/assets/19345275/22935602/5510b19e-f2d3-11e6-8323-526c1ba2e519.png)

Can you help me? Thanks

**Comment by juho-jaakkola** [comment]
Seems like a bug in the theme. Notifier does not use any special HTML elements for displaying the icon.

**Comment by annivzinal** [comment]
ok, that is what I was thinking... I've searched a lot in the code but found nothing, Thanks for answer.
